---
  extends: 'eslint:recommended'
  parser: 'babel-eslint'
  plugins:
    - 'import'
  env:
    browser: true
    node: true
    es6: true
    mocha: true
  ecmaFeatures:
    modules: true
  rules:
    # basic rules
    no-debugger: 1
    no-console: 0
    no-new: 0
    no-shadow: 1
    no-underscore-dangle: 0
    no-use-before-define: 0
    quotes:
        - 2
        - 'single'
        - 'avoid-escape'
    semi:
        - 2
        - 'always'
    no-extra-parens:
        - 2
        - 'functions'
    no-unexpected-multiline:
        - 2
    complexity:
        - 1
        - 4
    dot-location:
        - 2
        - 'property'
    no-caller: 2
    no-empty-label: 2
    no-magic-numbers: 2
    no-multi-str: 2
    no-proto: 2
    no-return-assign: 2
    no-script-url: 2
    # import plugin rules
    import/no-unresolved: 2
    import/named: 2
    import/namespace: 2
    import/default: 2
    import/export: 2
    import/imports-first: 2
    import/no-duplicates: 2
